print("Willkommen zur automatischen Zimmer Analyse")
größe = input("Bitte geb die Größe des Zimmers an klein/groß")
print("Das Zimmer ist also" + größe)
fenster = input("Wie viele Fenster hat das Zimmer?")
print("Das Zimmer hat also soviele Fenster:" + fenster)
farbe = input("Welche Farbe haben die Wände?")
print("Die wände sind also" + farbe)
boden = input("Aus welchem Material besteht der Fußboden?")
print("Der Fußboden besteht also aus:" + boden)
nutzung = input("Für was möchtest du dieses Zimmer nutzen?")
print("Du möchtest dieses Zimmer also nutzen als:" + nutzung)
möbel = input("Sind in diesem Zimmer schon Möbel vorhanden?")
print("Möbel?" + möbel)
licht = input("Wie viele Lichtschlater gibt es in diesem Raum?")
print("Lichtschlater vorhanden:" + licht)
balkon = input("Hat dieses Zimmer einen Balkon?")
print("Balkon:" +balkon)
etage = input("In welcher Etage bifindet sich das Zimmer?")
print("Das Zimmer befindet sicvh also in Etage:" + etage)
wlan = input("Hat dieses Zimmer WLan?")
print("WLan vorhanden:" + wlan)
print("Zimmer Analyse abgeschlossen Viele Dank für Ihre Zeit")